name: Deploy VuePress Site

on:
  # 当代码推送到 master 分支时触发此工作流
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # 检出代码到工作区
        uses: actions/checkout@v3
        with:
          # 拉取所有历史记录，用于后续可能的版本对比等操作
          fetch-depth: 0

      - name: Set up Node.js
        # 设置 Node.js 环境，可根据项目需求选择合适版本
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        # 缓存依赖，提高构建速度
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        # 安装项目依赖
        run: npm ci

      - name: Build VuePress site
        # 执行 VuePress 构建命令
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        # 将构建后的文件部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist